### ISSUE TITLE
Úkol č. 2 zpětná vazba

### ISSUE THREAD

**Issue by ifischerova** [VeronikaGabrielova/PROJEKT-Vizitka#1]
Ahoj Verčo, super práce 👍 Posílám pár tipů :-)

- [x] když je `font-family` a `font-size` na `<body>`, neni třeba zvlášť dávat na tlačítka, pokud je hodnota ve vlastnostech stejná.
- [x]  třídy `odsazeni1` a `odsazeni2`  jde úplně smazat a využít spodní `margin` `h1` + přidat `margin-top` k tlačítku twitteru.
- [x] tlačítka by bylo lepší vyřešit jako `<a>` a ty pak nastylovat (sdružit tam všechny vlastnosti z `<button>` a `<a>`). Tlačítka tak budou klikatelná kdekoli - teď je v klikatelné jen pokud uživatel kliká přímo na text/link, tzn. většina plochy tlačítka jako tlačítko nefunguje.  Zároveň si tím ušetříš dost kódu, protože většinu vlastností (snad až na barvu pozadí) budou mít obě tlačítka spolešných. 
[hint, jak udělat tlačítko z odkazu](https://stackoverflow.com/questions/8357058/how-to-make-an-html-anchor-tag-or-link-look-like-a-button)
- [x] k pseudotřídě `:hover` bych přidala ještě  `:focus`

**Comment by VeronikaGabrielova** [comment]
Ahoj Ivko, díky za tipy. Mám opraveno, hned kód vypadá lépe :-).

**Comment by ifischerova** [comment]
Ahoj Verčo, paráda :-)
